name: 'bo'

model:
    _target_: algorithms.BO
    active_dims: 15
    n_init: 10
    init_sampler_type: 'permutation'
    acqf_init_sampler_type: 'permutation'
    acqf_type: 'EI'
    acqf_opt_type: 'ea'
    kernel_type: 'vs'
    fillin_type: 'best_pos'
    device: 'cpu'